<?php

use App\Controllers\AdminController;
use App\Controllers\AuthController;
use App\Controllers\PublicController;

$router->get('/', [PublicController::class, 'home']);
$router->get('/robots.txt', [PublicController::class, 'robots']);
$router->get('/sitemap.xml', [PublicController::class, 'sitemap']);
$router->get('/mapa-strony', [PublicController::class, 'htmlSitemap']);
$router->get('/archiwum', [PublicController::class, 'archive']);
$router->get('/inauguracja-studencka', [PublicController::class, 'eventTypePage']);
$router->get('/integracja-studencka', [PublicController::class, 'eventTypePage']);
$router->get('/otrzesiny-studenckie', [PublicController::class, 'eventTypePage']);
$router->get('/juwenalia', [PublicController::class, 'eventTypePage']);
$router->get('/studencki-clubbing', [PublicController::class, 'eventTypePage']);
$router->get('/polowinki-studenckie', [PublicController::class, 'eventTypePage']);
$router->get('/andrzejki-studenckie', [PublicController::class, 'eventTypePage']);
$router->get('/walentynki-studenckie', [PublicController::class, 'eventTypePage']);
$router->get('/mikolajki-studenckie', [PublicController::class, 'eventTypePage']);
$router->get('/sylwester-studencki', [PublicController::class, 'eventTypePage']);
$router->get('/student-party-travel', [PublicController::class, 'eventTypePage']);
$router->get('/miasta', [PublicController::class, 'cities']);
$router->get('/miasta/{slug}', [PublicController::class, 'city']);
$router->get('/polityka-prywatnosci', [PublicController::class, 'privacyPolicy']);
$router->get('/polityka-cookies', [PublicController::class, 'cookiesPolicy']);
$router->get('/regulamin', [PublicController::class, 'terms']);
$router->get('/wycofaj-zgody', [PublicController::class, 'consentLookup']);
$router->post('/wycofaj-zgody', [PublicController::class, 'consentLookupSubmit']);
$router->get('/rezygnacja/{token}', [PublicController::class, 'unsubscribe']);
$router->post('/rezygnacja/{token}', [PublicController::class, 'unsubscribeUpdate']);
$router->get('/news/{slug}', [PublicController::class, 'newsArticle']);
$router->get('/wydarzenia', [PublicController::class, 'events']);
$router->get('/wydarzenia/{slug}', [PublicController::class, 'event']);
$router->post('/kontakt-marketingowy', [PublicController::class, 'marketingSignup']);
$router->post('/powiadom-o-biletach', [PublicController::class, 'ticketWaitlistSignup']);
$router->post('/kontakt-partnerski', [PublicController::class, 'partnerContact']);
$router->post('/analityka/klikniecie', [PublicController::class, 'trackEventClick']);

$router->get('/admin/login', [AuthController::class, 'login']);
$router->post('/admin/login', [AuthController::class, 'authenticate']);
$router->get('/admin/login/kod', [AuthController::class, 'code']);
$router->post('/admin/login/kod', [AuthController::class, 'verifyCode']);
$router->post('/admin/logout', [AuthController::class, 'logout']);

$router->get('/admin/install', [AdminController::class, 'install']);
$router->post('/admin/install', [AdminController::class, 'installRun']);
$router->get('/admin', [AdminController::class, 'dashboard']);
$router->get('/admin/wydarzenia', [AdminController::class, 'events']);
$router->get('/admin/wydarzenia/nowe', [AdminController::class, 'eventCreate']);
$router->post('/admin/wydarzenia', [AdminController::class, 'eventStore']);
$router->get('/admin/wydarzenia/{id}/edycja', [AdminController::class, 'eventEdit']);
$router->post('/admin/wydarzenia/{id}', [AdminController::class, 'eventUpdate']);
$router->post('/admin/wydarzenia/{id}/powiadom-bilety', [AdminController::class, 'eventNotifyTickets']);
$router->post('/admin/wydarzenia/{id}/usun', [AdminController::class, 'eventDelete']);
$router->get('/admin/newsy', [AdminController::class, 'news']);
$router->get('/admin/newsy/nowy', [AdminController::class, 'newsCreate']);
$router->post('/admin/newsy', [AdminController::class, 'newsStore']);
$router->get('/admin/newsy/{id}/edycja', [AdminController::class, 'newsEdit']);
$router->post('/admin/newsy/{id}', [AdminController::class, 'newsUpdate']);
$router->post('/admin/newsy/{id}/usun', [AdminController::class, 'newsDelete']);
$router->get('/admin/kontakty', [AdminController::class, 'contacts']);
$router->get('/admin/powiadomienia-bilety', [AdminController::class, 'ticketWaitlist']);
$router->get('/admin/analityka', [AdminController::class, 'analytics']);
$router->post('/admin/analityka/reset-sezonu', [AdminController::class, 'analyticsReset']);
$router->get('/admin/administratorzy', [AdminController::class, 'admins']);
$router->post('/admin/administratorzy', [AdminController::class, 'adminStore']);
$router->post('/admin/kontakty/email', [AdminController::class, 'contactsEmail']);
$router->get('/admin/kontakty/export', [AdminController::class, 'contactsExport']);
$router->post('/admin/test-email', [AdminController::class, 'testEmail']);
